### ISSUE TITLE
Atomics without anyone on Shield wall.

### ISSUE THREAD

**Issue by anorek-sys** [ronaldossendrijver/treachery.online#100]
It seems that atomics card is working regardless if you are on the wall or not

[atomics.json](https://github.com/user-attachments/files/17294729/atomics.json)

**Comment by Simon-Noble** [comment]
You do not need to be on the shield wall, only adjacent to it. Did this happen without having forces adjacent to the shield wall?

**Comment by anorek-sys** [comment]
Checked my save... you were right! It seems that my army was in the middle sector of Pasty Mesa.
Apologies if I wasted your time troubleshooting this

**Comment by ronaldossendrijver** [comment]
@Simon-Noble Thanks for answering this one :)
