### ISSUE TITLE
Nexus cards should be handed out between spice blows not at the end

### ISSUE THREAD

**Issue by Simon-Noble** [ronaldossendrijver/treachery.online#102]

**Comment by ronaldossendrijver** [comment]
Hi @Simon-Noble, are you sure about this? I believe it should be completely at the end of the phase, at least, according to the rulebook:
<img width="318" alt="image" src="https://github.com/user-attachments/assets/7563d6f4-cdf1-43eb-b1da-30a1f6968002">

**Comment by Simon-Noble** [comment]
I think you may be right but I'm not sure, I spent some time finding evidence for my issue, but I think the rules are actually just unclear. I think we can close this issue at least until I have better evidence
