### ISSUE TITLE
Karama played against Tilexu does not prevent them reviving as ghola

### ISSUE THREAD

**Issue by goodygoodygoody90** [ronaldossendrijver/treachery.online#39]
I played a Karama to prevent my 7 strength leader being stolen by Tilexu, but they still revived him to their off planet resources. 
[savegame (10).json](https://github.com/ronaldossendrijver/treachery.online/files/14888182/savegame.10.json)

**Comment by ronaldossendrijver** [comment]
Thanks for reporting, I changed the way Karama prevents revival to work for the entire turn (it only worked for 1 instance).
