### ISSUE TITLE
Cannot play family atomics

### ISSUE THREAD

**Issue by RDPixel123** [ronaldossendrijver/treachery.online#54]
Thank you for your service sir! I just played the board game on Saturday and now I'm hooked. It looks like I have no option to play family atomics in this save file 
[savegame.json](https://github.com/ronaldossendrijver/treachery.online/files/14912062/savegame.json)

**Comment by RDPixel123** [comment]
Never mind misunderstood the rule!

**Comment by ronaldossendrijver** [comment]
No problem!
