### ISSUE TITLE
Cannot revive and Sardaukar still cost spice without 

### ISSUE THREAD

**Issue by RDPixel123** [ronaldossendrijver/treachery.online#55]
[savegame (1).json](https://github.com/ronaldossendrijver/treachery.online/files/14914699/savegame.1.json)

Seems like I never get the opportunity to revive leaders when I have the spice or the right card. And I still have to pay spice to commit sardaukar

**Comment by ronaldossendrijver** [comment]
Hi! According to the rules, you can only start reviving leaders using normal revival after all your leaders have died. Only the Tleilaxu faction can allow you to revive leaders erly.

You are allowed to revive a leader with the Tleilaxu Ghola card though, I've tested that.

Why do you think you don't have to pay spice to support your Sardaukar? You only dont have to pay for them if you're playing with the Homeworlds from the latest expansion, and in the game you checked you didn't enable Homeworlds.

**Comment by sirrus233** [comment]
I think I may understand the complaint that is being made here. There seems to be a bug where battles *force* you to pay spice to commit Sardaukar, even if you can't or don't want to.

**Comment by ronaldossendrijver** [comment]
I found the Sardaukar issue, will be fixed in the next update!
