### ISSUE TITLE
The discovery token glitch that kills units

### ISSUE THREAD

**Issue by RatManAntics** [ronaldossendrijver/treachery.online#71]
Because of discovery tokens and some spots can in theory get spice twice (eg. rock outcropping with discovery token comes up round 2 and in round 3 normal rock outcropping comes up) when that happens it kills all the troops in that area as if it was a worm.

also now whenever I try to undo and action it takes me back ages in the game, so if someone makes a mistake and I click confirm it accidentally takes me back sometimes turns ago.

Thank you!

**Comment by ronaldossendrijver** [comment]
Hi! This is intentional. According to the expansion 3 rulebook, when a discovery card is drawn, all spice and forces already in the territory where the spice should be placed are destroyed first.

About the undo button: this is indeed a bug and will be fixed in the next release.
