### ISSUE TITLE
Moritanit Terror Placement

### ISSUE THREAD

**Issue by Antidisestablishment** [ronaldossendrijver/treachery.online#75]
When selecting a stronghold to place terror, the list is blank and the system doesn't let me place new terror tokens.

it repeats every collection phase (when you get to place them).

This wrecks the game for Moritani.

![image](https://github.com/ronaldossendrijver/treachery.online/assets/170186855/eb922f69-9914-42ce-b69d-a2c4aeb7f082)

**Comment by Antidisestablishment** [comment]
Maybe it's a one-off, but it's unfortunate...

**Comment by ronaldossendrijver** [comment]
> Maybe it's a one-off, but it's unfortunate...

Hi! Terror placement is during Mentat, not during Collection. During collection, Moritani can move tokens when their Homeworld threshold allows it. But maybe the user interface is confusing?
