### ISSUE TITLE
Not the aggressor after using Juice of Sapho 

### ISSUE THREAD

**Issue by ALDRO88** [ronaldossendrijver/treachery.online#77]
![Uploading Capture d’écran, le 2024-06-04 à 23.08.58.png…]()
[savegame - 2024-06-04T230903.328.json](https://github.com/user-attachments/files/15572628/savegame.-.2024-06-04T230903.328.json)

**Comment by ALDRO88** [comment]
Even in a second attempt in which I use the juice directly during the fight, I lose the battle...
<img width="1440" alt="Capture d’écran, le 2024-06-04 à 23 08 58" src="https://github.com/ronaldossendrijver/treachery.online/assets/167587685/3cd64069-486b-4dfa-b33a-270f9cb8eba7">
[savegame - 2024-06-04T231402.878.json](https://github.com/user-attachments/files/15572627/savegame.-.2024-06-04T231402.878.json)

**Comment by ronaldossendrijver** [comment]
Hi @ALDRO88! This is not a bug, you forgot that Emperor has the Habbanya Sietch Stronghold Advantage, which means they always win ties in fights there.
