### ISSUE TITLE
ECAZ + Fremen Alliance Bug

### ISSUE THREAD

**Issue by Deltabar74** [ronaldossendrijver/treachery.online#78]
When allied Ecaz does not have to spice dial Fremen forces to get the most out of them.

Source: The designer of the game

Link: https://youtu.be/ooLEVWDzpV8?si=xBy47Zk2ABrcoEVE

Both in video and in the comments this is clarified.

**Comment by ronaldossendrijver** [comment]
Hi @Deltabar74 thanks for reporting this, I didn't know... I will fix this in the next update.
