### ISSUE TITLE
Reviving more troops than requested

### ISSUE THREAD

**Issue by ALDRO88** [ronaldossendrijver/treachery.online#82]
On the last move of the game save, I ask to revive one cyborg, but end up reviving all my troops for free instead... Normal?
<img width="703" alt="Capture d’écran, le 2024-06-29 à 23 43 19" src="https://github.com/ronaldossendrijver/treachery.online/assets/167587685/8c3f0366-c30d-4ad9-8e81-28ec10784686">
<img width="697" alt="Capture d’écran, le 2024-06-29 à 23 43 31" src="https://github.com/ronaldossendrijver/treachery.online/assets/167587685/47fbd011-5398-45e2-8d67-89a62d5def7a">
[savegame - 2024-06-29T234332.716.json](https://github.com/user-attachments/files/16043053/savegame.-.2024-06-29T234332.716.json)

**Comment by ALDRO88** [comment]
Shouldn't this bonus be applied when I ''pay'' for reviving a cyborg?

**Comment by ronaldossendrijver** [comment]
You are right, this issue has now been fixed, thanks for reporting!
