### ISSUE TITLE
Cyborgs count as full strenght without having to pay spice

### ISSUE THREAD

**Issue by ALDRO88** [ronaldossendrijver/treachery.online#83]
[savegame - 2024-06-30T010323.132.json](https://github.com/user-attachments/files/16043265/savegame.-.2024-06-30T010323.132.json)
<img width="723" alt="Capture d’écran, le 2024-06-30 à 01 03 20" src="https://github.com/ronaldossendrijver/treachery.online/assets/167587685/ce9aab43-2c8e-45ae-afda-b2928d9296b2">

**Comment by ronaldossendrijver** [comment]
This issue has been fixed.
