### ISSUE TITLE
CHOAM Karama ability not working when using a Truthtrance as a Karama

### ISSUE THREAD

**Issue by rusty-ccv** [ronaldossendrijver/treachery.online#92]
I found an issue when playing CHOAM and occupying the Shrine discovery token. 
The shrine allows a Truthtrance treachery card to be played as a Karama card. This works for the standard Karama abilities and gives me the faction-specific dropdown for CHOAM's discard a card for 3 spice ability but won't let me use it, telling me "You don't have a Karama card" when trying to discard.

![Screenshot from 2024-07-17 12-57-27](https://github.com/user-attachments/assets/68bed972-6879-42f9-9fd4-671e7ed09167)

[savegame.json](https://github.com/user-attachments/files/16258719/savegame.json)

**Comment by Simon-Noble** [comment]
Source of the issue seems to be line 46 in Shared.Events.KaramaBrownDiscard.

Removing the line would likely fix the issue, as the line should never be accessed in a situation where it would correctly return false.

**Comment by Simon-Noble** [comment]
Actually this would not fix it, there must be a little more digging.
